name = "furyengi-newsletter"
main = "cloudflare-newsletter-worker.js"
compatibility_date = "2026-10-01"
workers_dev = false

routes = [
  { pattern = "furyengi.cv/api/newsletter", zone_id = "f4c30d658d092120edbc9521077a9066" }
]

kv_namespaces = [
  { binding = "SUBSCRIBERS", id = "4ffe6796df4c41ccaa37c482e70def2d" }
]
